# Generated by Django 5.0.3 on 2024-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
    ]
